import "@/styles/globals.css";
import { Toaster } from "@/components/ui/toaster"
import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import { AppSidebar } from "@/components/app-sidebar"
import { SidebarInset, SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"

import { TRPCReactProvider } from "@/trpc/react";
import { Theme } from "@radix-ui/themes";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      
      <body>
      <SidebarProvider>
      <AppSidebar />
      <SidebarInset className="flex flex-col">
      <SidebarTrigger />
        <TRPCReactProvider>{children}</TRPCReactProvider>
        <Toaster />
      </SidebarInset>
      </SidebarProvider>
      </body>
    </html>
  );
}
